name: Hugo Deploy ğŸŒ¤ï¸

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      VIMEO_TOKEN:
    inputs:
      S3_BUCKET_NAME:
        required: true

jobs:
  workflows-lint:
    uses: gauntface/workflows-static-site/.github/workflows/lint.yaml@main

  genimgs:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go  ğŸ› ï¸
        uses: actions/setup-go@v3
        with:
          go-version: '^1.18.3'

      - name: Install action Go Deps ğŸŒ
        run: |
          go install github.com/gauntface/go-html-asset-manager/v4/cmds/genimgs@latest
      - name: Generate images ğŸ–¼ï¸
        run: genimgs

  workflows-build:
    uses: gauntface/workflows-static-site/.github/workflows/hugo-build.yaml@main

  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact ğŸ“¦
        uses: actions/download-artifact@v3
        with:
          name: hugo-site
          path: hugo-site
      - name: Publish to AWS
        run: npx --package @gauntface/cli gauntface aws s3 deploy-static-site --directory="./public/" --bucket_name="${{ inputs.S3_BUCKET_NAME }}" --delete_exclude="generated/*"
        shell: bash
